sudo: required
dist: trusty

before_install:
  - echo 'deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse' | sudo tee -a /etc/apt/sources.list
  - sudo apt-get -qq update
  - sudo apt-get install -y gnupg shellcheck

git:
  depth: 3

script: ./test.sh